name: Login
version: '${project.version}'
main: fr.mrsuricate.login.Main
api-version: 1.19
authors: [ MrSuricate ]
commands:
  login:
    description: login
    aliases:
      - l
  register:
    description: register